<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Post extends Model
{
    use HasFactory;

    protected $casts = [
        'created_at'  => 'date:Y-m-d h:i:s',
    ];

//    protected $guarded = ['id']; //wszytsko jest fillable oprócz id
    protected $fillable = ['title', 'excerpt', 'body']; // pozwala tworzyć nowe obiekty z poziomu tinkera w następujący sposób: php artisan tinker     Post::create(['title' => 'cos', 'excerpt' => 'cos])

    //to pozwoli za każdym razem wczytać te 2 dane przy zapytaniach SQl - przydatne bo rozwiazuje problem n+1 ale nie zawsze musimy chcieć te dane pobrać także używać z rozsądkiem - alternatywa jest w web.php 'posts' => $author->posts->load(['category', 'author'])
    /**
     * @var string[]
     */
    protected $with = ['category', 'author'];

    //to jest potrzebne, żeby znaleźć rekord z bazy po slug-u gdy w Route mamy {post} a nie {post:slug}
    public function getRouteKeyName(): string
    {
//        return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
        return 'slug';
    }

    public function scopeFilter(Builder $query, array $filters): void
    {
        $query->when(
            $filters['admin_search'] ?? false,
            fn (Builder $query, mixed $search): Builder =>
            $query->where(
                function (Builder $query) use ($search): Builder {
                    /** @var string $searchAsString */
                    $searchAsString = $search;

                    return $query->where('title', 'like', '%' . $searchAsString . '%');
                }
            )
        );

        $query->when(
            $filters['search'] ?? false,
            fn (Builder $query, mixed $search): Builder =>
            $query->where(
                function (Builder $query) use ($search): Builder {
                    /** @var string $searchAsString */
                    $searchAsString = $search;

                    return $query->where('title', 'like', '%' . $searchAsString . '%')
                        ->orWhere('body', 'like', '%' . $searchAsString . '%');
                }
            )
        );

        $query->when(
            $filters['category'] ?? false,
            fn (Builder $query, mixed $category): Builder =>
            $query->whereHas(
                'category',
                fn (Builder $query): Builder =>
                $query->where('slug', $category)
            )
        );

        $query->when(
            $filters['author'] ?? false,
            function (Builder $query, mixed $author): Builder {
                /** @var string $authorAsString */
                $authorAsString = $author;

                return $query->whereHas(
                    'author',
                    fn (Builder $query): Builder => $query->where('username', strtolower($authorAsString)),
                );
            }
        );
    }

    public function scopeFilterForCreator(Builder $query, array $filters): void
    {
        $query->when(
            $filters['search']['search'] ?? false,
            fn (Builder $query, mixed $search): Builder =>
            $query->where(
                function (Builder $query) use ($search): Builder {
                    /** @var string $searchAsString */
                    $searchAsString = $search;
                    return $query->where('title', 'like', '%' . $searchAsString . '%');
                }
            )
        );

        $query->when(
            $filters['id'] ?? false,
            function (Builder $query, mixed $author): Builder {
                /** @var string $authorAsString */
                $authorAsString = $author;

                return $query->whereHas(
                    'author',
                    fn (Builder $query): Builder => $query->where('posts.user_id', strtolower($authorAsString)),
                );
            }
        );
    }

    public function comments(): HasMany
    { // Laravel zakłada, że klucz obcy będzie nazywał się user_id - nazwaMetody_id
        return $this->hasMany(Comment::class);
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    public function author(): BelongsTo
    { // Laravel zakłada, że klucz obcy będzie nazywał się user_id - nazwaMetody_id
        return $this->belongsTo(User::class, 'user_id');
    }
}
